### 주문 생성
POST http://localhost:8000/order-service/f9b196ac-2df8-4c39-a217-c9d61a5a6926/orders
Content-Type: application/json

{
  "productId": "CATALOG-002",
  "qty": 5,
  "unitPrice": 1000
}

### 사용자 전체 주문 조회
GET http://localhost:8000/order-service/f9b196ac-2df8-4c39-a217-c9d61a5a6926/orders