### 사용자 회원가입/등록
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "primarchan@gmail.com",
  "name": "Chris An",
  "password": "1111"
}

### 전체 사용자 정보 조회
GET http://localhost:8000/user-service/users
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIwOWUwM2NlMy1iNzA2LTRlN2EtODE5NC04MGI0NjA5NzE1MzQiLCJleHAiOjE3MTI5MDk4OTUsImlhdCI6MTcxMjgyMzQ5NX0.h7j_SHPguONNEBq6gkq6Gk7PrX00mc7FOGYSCrM1F4-ny7wsC2gIO8h8lctOd84D

### 사용자 정보 조회
GET http://localhost:8000/user-service/users/a686eed8-7132-4964-927d-ac78edb20bbb
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIwOWUwM2NlMy1iNzA2LTRlN2EtODE5NC04MGI0NjA5NzE1MzQiLCJleHAiOjE3MTI5MDk4OTUsImlhdCI6MTcxMjgyMzQ5NX0.h7j_SHPguONNEBq6gkq6Gk7PrX00mc7FOGYSCrM1F4-ny7wsC2gIO8h8lctOd84D

### 사용자 로그인 요청
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
  "email": "primarchan@gmail.com",
  "password": "1111"
}

### 전체 상품 목록 조회
GET http://localhost:8000/catalog-service/catalogs

### 주문 생성
POST http://localhost:8000/order-service/f36a31d8-7364-4385-b219-efebdb69d759/orders
Content-Type: application/json

{
  "productId": "CATALOG-003",
  "qty": 5,
  "unitPrice": 1000
}

### 사용자 전체 주문 조회
GET http://localhost:8000/order-service/f36a31d8-7364-4385-b219-efebdb69d759/orders

### API GATEWAY Actuator health 상태 요청
GET http://localhost:8000/actuator/health

### USER-SEEVICE Actuator health 상태 요청
GET http://localhost:8000/user-service/actuator/health

### USER-SEEVICE Actuator refresh 요청
POST http://localhost:8000/user-service/actuator/refresh

### Spring Cloud Bus 를 통한 Actuator refresh 요청
POST http://localhost:8000/user-service/actuator/busrefresh

### 대칭키를 이용한 암호화 요청
POST http://localhost:8888/encrypt
Content-Type: text/plain

D9qQQvKlg9b_WD_Q0SrvL8hlbELu9MiLobrK5AvadOo=

### 대칭키를 이용한 복호화 요청
POST http://localhost:8888/decrypt
Content-Type: text/plain

AYAw/aOxc8S5jSeIpVrku7x4BHDpAE0ELNqe+BvCkx3SndLo+uOl3VaPqqFz4RJdGGjCjTde3F1KZRTFNfOYpBQunkqnyCvwsZigJ4Qx9NIloJU2SaizwQFQVf5BV/KfXemSSPPi4F+nQIz2cDEgbCx3+RQmsNAmHeFJ4vtBTS8cFWFe+YUJWYOUR0KVRU+xDUceFXSMfIKFZ7OI491EKDJmxxYmRw5rro0jpfkYCjeyspNHWn533AETShlGox6gaCcwn+suv5y+K+u7lRKrjBMmwsdHNywNS1OsYnAOk/YXSIHlQmjJxP6UoLQXMDdOy6HvxhBRfNd24ZEMOmeUsYexTCbxLziJdFufX/h+heeVrORUjSzUBJ8ebZB1X2jpQ+WDU6M891mK35AMJx5c6In2zMpSEmsTX6KtYdGrwZRerod/Vp0T5Zz9luz7HmKBmwPuq2q+UoaSYers2ueCTzspgTxv4olxfMXbmIB/nzHvhRlVwWUlHicFC0rnWLtHLjnIOvDkCB87Z7IFsLsikX6H6IgocLQipII5OikPzmq3ltnPD+y4vZOo9EgOunDN3DehCG7uyFIjHCIvufb6EaWO
